Increase build number, check SRC and PKG dirs, set sysconfdir, add exits, add requirements file

diff --git a/libmpcdec.SlackBuild b/libmpcdec.SlackBuild
--- a/libmpcdec.SlackBuild
+++ b/libmpcdec.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# SlackBuild for mpcdec
+# SlackBuild for libmpcdec
 # Written by Georgi D. Sotirov <gdsotirov@dir.bg>
 #
 
@@ -8,49 +8,78 @@
 
 NAME=libmpcdec
 VERSION=1.2.6
-BUILD=1
+BUILD=2
+ARCH=${ARCH:-i486}
 
+TMP=${TMP:-/tmp}
+CWD=${CWD:-`pwd`}
+
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
+SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract the source
 cd $TMP
-tar -jxvf $CWD/$NAME-$VERSION.tar.bz2
+tar -jxvf $CWD/$NAME-$VERSION.tar.bz2 || exit 1
 SRC=$TMP/$NAME-$VERSION
 cd $SRC
 fix_source
 
+# Configure
 CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
+            --sysconfdir=/etc \
             --mandir=/usr/man \
             --enable-shared=yes \
-            --enable-static=no
+            --enable-static=no || exit 2
 
-make || exit 1
+# Build
+make -j4 all || exit 3 
 
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
+# Install
+make DESTDIR=$PKG install || exit 3
 
-make -e DESTDIR=$PKG install
-
-( cd $PKG; strip_lib )
+# Prepare
+bin_perms $PKG
+( cd $PKG; strip_bin; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
 
 mkdir -p $PKG/install
-install -m 644 $CWD/slack-desc     $PKG/install
+install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
+install -m 644 $CWD/slack-required $PKG/install/slack-required
 
 mkdir -p $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION
+install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-desc
+install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
+install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Pack
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
-makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
+makepkg -l y -c n -p $PKG_DIR/$PKGNAME.tgz
 cd $PKG_DIR
 md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
-  rm -r $SRC
-  rm -r $PKG
+  rm -rf $SRC
+  rm -rf $PKG
 fi
 
